<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<div class="blog-toolbar blog-toolbar-top">
   <?php echo $this->getChildHtml('blog_comments_toolbar'); ?>
</div>
<?php 
$_hpImages = Mage::helper('blog/images');
$width  = 900;
$height = 587;
?>
<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
        <a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getImage() ? '<img  class="img-responsive" src="'. $_hpImages->resizeImg(basename($post->getImage()), $width, $height) .'">' : ''; ?></a>
        <div class="postTitle">
            <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
        </div>
		<div class="by post-info">
			<div class="postDetails">
				<?php $postCats = $post->getCats(); ?>
				<?php if (!empty($postCats)): ?>
					<?php //echo Mage::helper('blog')->__('Posted in'); ?>
					<?php foreach ($postCats as $data): ?>
						<!--<a href="<?php //echo $data['url']; ?>"><?php //echo $data['title']; ?></a>-->
					<?php endforeach; ?>
				<?php else: ?>
					<?php //echo Mage::helper('blog')->__('Posted'); ?>
				<?php endif; ?><i class="fa fa-user"></i><?php echo $this->__("By:"); ?> <span class="user"><?php echo $post->getUser(); ?></span>
			</div>

			<div class="post-time"><i class="fa fa-clock-o"></i><span><?php echo $post->getCreatedTime(); ?></span></div>
			<div class="post-comment">
			<i class="fa fa-comments-o"></i>
			<?php if ($this->getCommentsEnabled()): ?>
			<span class="comments">
				<?php if(count($post->getCommentCount()) > 0):?>
					<?php echo $post->getCommentCount() ?>
				<?php else:?>
					<?php echo $this->__('0');?>
				<?php endif;?>
				<a href="<?php echo $post->getAddress(); ?>#commentBox" > <?php echo Mage::helper('blog')->__('Comments'); ?></a>
			</span>
			<?php endif; ?>
			</div>
		</div>
		<!--<div class="tags"><?php //echo $this->getTagsHtml($post) ?></div>-->
		<?php echo $this->getBookmarkHtml($post) ?>
        <div class="postContent"><?php echo $post->getPostContent(); ?></div>
    </div>
<?php endforeach; ?>
<div class="blog-toolbar blog-toolbar-bottom">
<?php echo $this->getChildHtml('blog_comments_toolbar'); ?>
</div>
